name: ⚡️ Performance
description: Performance Issue Template 입니다.
title: "⚡️ Performance: "
labels: ["⚡️ Performance"]
body:
  - type: textarea
    id: target
    attributes:
      label: 성능 개선 및 최적화 대상
      description: 어떤 부분을 개선하나요?

  - type: textarea
    id: reason
    attributes:
      label: 이유
      description: 왜 필요한가요?

  - type: textarea
    id: changes
    attributes:
      label: 변경 내용
      
  - type: textarea
    id: tasks
    attributes:
      label: 작업 목록
      description: 구현해야 할 작업을 체크박스로 작성해주세요.
      value: |
        - [ ] 메모리 개선
    validations:
      required: true
